/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
-- All the data related to time are stored in unix time stamp and therefore, the data types for the time related data
-- are represented in BIGINT.
-- Since the database systems does not support adding default unix time to the database columns, the default data
-- storing is handled within the database queries.


-- TOPIC definition
CREATE TABLE IF NOT EXISTS `TOPIC` (
  `TOPIC_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `NAME` varchar(225) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `STATUS` enum('active', 'deregistered') NOT NULL DEFAULT 'active',
  `INITIATED_BY` varchar(32) NOT NULL DEFAULT 'USER',
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ACTIVE_NAME` varchar(225) GENERATED ALWAYS AS
    (CASE WHEN `STATUS` = 'active' THEN LOWER(`NAME`) ELSE NULL END) STORED,
  PRIMARY KEY (`TOPIC_ID`),
  CONSTRAINT UQ_TOPIC_ORG_ID UNIQUE (ORG_ID, TOPIC_ID),
  UNIQUE KEY `UQ_TOPIC_ORG_ACTIVE_NAME` (`ORG_ID`, `ACTIVE_NAME`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- EVENT definition
CREATE TABLE IF NOT EXISTS `EVENT` (
  `EVENT_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `GROUP_ID` varchar(128) NOT NULL,
  `TOPIC_ID` varchar(64) NOT NULL,
  `PAYLOAD` json NOT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`EVENT_ID`),
  CONSTRAINT `UQ_EVENT_ORG_ID` UNIQUE (`ORG_ID`, `EVENT_ID`),
  KEY `FK_E_TOPIC` (`TOPIC_ID`),
  KEY `IDX_EVENT_ORG_GROUP_TOPIC_CREATED` (`ORG_ID`, `GROUP_ID`, `TOPIC_ID`, `CREATED_AT`),
  KEY `IDX_EVENT_ORG_CREATED` (`ORG_ID`, `CREATED_AT` DESC),
  KEY `IDX_EVENT_ORG_TOPIC` (`ORG_ID`, `TOPIC_ID`),
  CONSTRAINT `FK_E_ORG_TOPIC` FOREIGN KEY (`ORG_ID`, `TOPIC_ID`) REFERENCES `TOPIC` (`ORG_ID`, `TOPIC_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- EVENT_PURPOSE definition
CREATE TABLE IF NOT EXISTS `EVENT_PURPOSE` (
  `EVENT_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `PURPOSE_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`EVENT_ID`, `PURPOSE_NAME`),
  KEY `IDX_EVENT_PURPOSE_NAME` (`PURPOSE_NAME`),
  KEY `IDX_EP_ORG` (`ORG_ID`, `EVENT_ID`),
  CONSTRAINT `FK_EVENT_PURPOSES_EVENT` FOREIGN KEY (`ORG_ID`, `EVENT_ID`) REFERENCES `EVENT` (`ORG_ID`, `EVENT_ID`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- SUBSCRIPTION definition
CREATE TABLE IF NOT EXISTS `SUBSCRIPTION` (
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `GROUP_ID` varchar(128) NOT NULL,
  `NAME` varchar(225) NOT NULL,
  `STATUS` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'active',
  `PURPOSE_FILTER_MODE` varchar(32) NOT NULL,
  `PURPOSE_SET_HASH` varchar(64) NOT NULL DEFAULT '',
  `CALLBACK_URL` varchar(512) DEFAULT NULL,
  `SHARED_SECRET` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DELIVERY_MODE` varchar(32) NOT NULL,
  `ACTIVE_NAME` varchar(225) GENERATED ALWAYS AS
    (CASE WHEN `STATUS` <> 'deleted' THEN LOWER(`NAME`) ELSE NULL END) STORED,
  PRIMARY KEY (`SUBSCRIPTION_ID`),
  CONSTRAINT UQ_SUB_ORG_ID UNIQUE (ORG_ID, SUBSCRIPTION_ID),
  UNIQUE KEY `UQ_SUB_ORG_ACTIVE_NAME` (`ORG_ID`, `ACTIVE_NAME`),
  KEY `IDX_SUB_STATUS_UPDATED` (`STATUS`, `UPDATED_AT`),
  KEY `IDX_SUB_MATCHING` (`ORG_ID`, `GROUP_ID`, `STATUS`),
  CONSTRAINT `CHK_S_STATUS` CHECK ((`STATUS` in (_utf8mb4'active', _utf8mb4'pending', _utf8mb4'stale', _utf8mb4'deleted'))),
  CONSTRAINT `CHK_SM_DELIVERY_MODE` CHECK ((`DELIVERY_MODE` in (_utf8mb4'webhook', _utf8mb4'poll')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS SUBSCRIPTION_TOPIC (
  ORG_ID VARCHAR(128) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  TOPIC_ID VARCHAR(64) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID, TOPIC_ID),
  KEY `IDX_ST_TOPIC` (ORG_ID, TOPIC_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_ST_SUB FOREIGN KEY (ORG_ID, SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (ORG_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_ST_TOPIC FOREIGN KEY (ORG_ID, TOPIC_ID) REFERENCES TOPIC (ORG_ID, TOPIC_ID)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- SUBSCRIPTION_PURPOSE definition
CREATE TABLE IF NOT EXISTS `SUBSCRIPTION_PURPOSE` (
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `PURPOSE_NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`SUBSCRIPTION_ID`, `PURPOSE_NAME`),
  KEY `IDX_SUB_PURPOSE_NAME` (`PURPOSE_NAME`),
  KEY `IDX_SP_ORG` (`ORG_ID`, `SUBSCRIPTION_ID`),
  CONSTRAINT `FK_SUBSCRIPTION_PURPOSES_SUBSCRIPTION` FOREIGN KEY (`ORG_ID`, `SUBSCRIPTION_ID`) REFERENCES `SUBSCRIPTION` (`ORG_ID`, `SUBSCRIPTION_ID`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- WEBHOOK_DELIVERY definition
CREATE TABLE IF NOT EXISTS `WEBHOOK_DELIVERY` (
  `DELIVERY_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `EVENT_ID` varchar(64) NOT NULL,
  `STATUS` varchar(32) NOT NULL DEFAULT 'pending',
  `ATTEMPT_COUNT` int NOT NULL DEFAULT '0',
  `NEXT_RETRY_AT` timestamp NULL DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DELIVERED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`DELIVERY_ID`),
  UNIQUE KEY `UQ_EDP_EVENT_SUB` (`EVENT_ID`, `SUBSCRIPTION_ID`),
  UNIQUE KEY `UQ_WD_ORG_DELIVERY` (`ORG_ID`, `DELIVERY_ID`),
  KEY `FK_EDP_SUB` (`SUBSCRIPTION_ID`),
  KEY `IDX_WD_ORG` (`ORG_ID`, `SUBSCRIPTION_ID`),
  KEY `IDX_WD_STATUS_CREATED` (`STATUS`, `CREATED_AT`),
  CONSTRAINT `FK_EDP_EVENT` FOREIGN KEY (`ORG_ID`, `EVENT_ID`) REFERENCES `EVENT` (`ORG_ID`, `EVENT_ID`),
  CONSTRAINT `FK_WD_ORG_SUB` FOREIGN KEY (`ORG_ID`, `SUBSCRIPTION_ID`) REFERENCES `SUBSCRIPTION` (`ORG_ID`, `SUBSCRIPTION_ID`),
  CONSTRAINT `CHK_WEBHOOK_DELIVERY_STATUS` CHECK ((`STATUS` in (_utf8mb4'pending', _utf8mb4'in_flight', _utf8mb4'delivered', _utf8mb4'completed', _utf8mb4'failed')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- WEBHOOK_DELIVERY_ACK definition
CREATE TABLE IF NOT EXISTS `WEBHOOK_DELIVERY_ACK` (
  `ACK_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `DELIVERY_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `COMPLETED_AT` timestamp NULL DEFAULT NULL,
  `COMPLETION_STATUS` varchar(32) NOT NULL,
  `COMPLETION_EVIDENCE` varchar(512) NOT NULL,
  PRIMARY KEY (`ACK_ID`),
  UNIQUE KEY `UQ_EDA_DELIVERY` (`DELIVERY_ID`),
  KEY `IDX_EDA_COMPLETION_STATUS` (`COMPLETION_STATUS`),
  KEY `IDX_WDA_ORG` (`ORG_ID`, `DELIVERY_ID`),
  CONSTRAINT `FK_EDA_DELIVERY` FOREIGN KEY (`ORG_ID`, `DELIVERY_ID`) REFERENCES `WEBHOOK_DELIVERY` (`ORG_ID`, `DELIVERY_ID`),
  CONSTRAINT `CHK_EDA_COMPLETION_STATUS` CHECK ((`COMPLETION_STATUS` in (_utf8mb4'completed', _utf8mb4'ack', _utf8mb4'disputed', _utf8mb4'partial')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;


-- WEBHOOK_DELIVERY_AUDIT definition
CREATE TABLE IF NOT EXISTS `WEBHOOK_DELIVERY_AUDIT` (
  `AUDIT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `EVENT_ID` varchar(64) DEFAULT NULL,
  `DELIVERY_ID` varchar(64) DEFAULT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `RESPONSE_CODE` varchar(16) DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ATTEMPT_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`AUDIT_ID`),
  KEY `IDX_EA_DELIVERY` (`DELIVERY_ID`, `ATTEMPT_AT`),
  KEY `IDX_EA_EVENT` (`EVENT_ID`),
  CONSTRAINT `FK_EA_DELIVERY` FOREIGN KEY (`DELIVERY_ID`) REFERENCES `WEBHOOK_DELIVERY` (`DELIVERY_ID`) ON DELETE SET NULL,
  CONSTRAINT `FK_EA_EVENT` FOREIGN KEY (`EVENT_ID`) REFERENCES `EVENT` (`EVENT_ID`) ON DELETE SET NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- POLL_DELIVERY definition
CREATE TABLE IF NOT EXISTS `POLL_DELIVERY` (
  `DELIVERY_ID` varchar(64) NOT NULL,
  `ORG_ID` varchar(128) NOT NULL,
  `SUBSCRIPTION_ID` varchar(64) NOT NULL,
  `EVENT_ID` varchar(64) NOT NULL,
  `STATUS` varchar(32) NOT NULL DEFAULT 'pending',
  `ERROR_CODE` varchar(64) DEFAULT NULL,
  `ERROR_DETAIL` varchar(1024) DEFAULT NULL,
  `CREATED_AT` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `COMPLETED_AT` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`DELIVERY_ID`),
  UNIQUE KEY `UQ_EDPL_EVENT_SUB` (`EVENT_ID`, `SUBSCRIPTION_ID`),
  KEY `IDX_EDPL_SUB` (`SUBSCRIPTION_ID`, `STATUS`, `CREATED_AT`),
  KEY `IDX_PD_ORG` (`ORG_ID`, `SUBSCRIPTION_ID`),
  CONSTRAINT `FK_EDPL_EVENT` FOREIGN KEY (`ORG_ID`, `EVENT_ID`) REFERENCES `EVENT` (`ORG_ID`, `EVENT_ID`),
  CONSTRAINT `FK_PD_ORG_SUB` FOREIGN KEY (`ORG_ID`, `SUBSCRIPTION_ID`) REFERENCES `SUBSCRIPTION` (`ORG_ID`, `SUBSCRIPTION_ID`),
  CONSTRAINT `CHK_POLL_DELIVERY_STATUS` CHECK ((`STATUS` in (_utf8mb4'pending', _utf8mb4'acknowledged', _utf8mb4'err')))
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;
