-- Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
--
-- WSO2 LLC. licenses this file to you under the Apache License,
-- Version 2.0 (the "License"); you may not use this file except
-- in compliance with the License.
-- You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in writing,
-- software distributed under the License is distributed on an
-- "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
-- KIND, either express or implied. See the License for the
-- specific language governing permissions and limitations
-- under the License.


-- Database DDL for DPDP Event Notifications (PostgreSQL). Mirrors mysql.sql.

-- Emulates MySQL's ON UPDATE CURRENT_TIMESTAMP: bump only when the statement left UPDATED_AT
-- untouched and some other column actually changed.
CREATE OR REPLACE FUNCTION DPDP_TOUCH_UPDATED_AT() RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.UPDATED_AT IS NOT DISTINCT FROM OLD.UPDATED_AT AND ROW(NEW.*) IS DISTINCT FROM ROW(OLD.*) THEN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS TOPIC (
  TOPIC_ID     VARCHAR(64)  NOT NULL,
  ORG_ID       VARCHAR(128) NOT NULL,
  NAME         VARCHAR(225) NOT NULL,
  DESCRIPTION  VARCHAR(255) DEFAULT NULL,
  STATUS       VARCHAR(16)  NOT NULL DEFAULT 'active',
  INITIATED_BY VARCHAR(32)  NOT NULL DEFAULT 'USER',
  CREATED_AT   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (TOPIC_ID),
  CONSTRAINT UQ_TOPIC_ORG_ID UNIQUE (ORG_ID, TOPIC_ID),
  CONSTRAINT CHK_TOPIC_STATUS CHECK (STATUS IN ('active', 'deleted'))
);
-- Same rule as mysql.sql's generated ACTIVE_NAME key: one active topic per name per org,
-- case-insensitively, while deleted topics keep their names.
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TOPIC_ORG_ACTIVE_NAME ON TOPIC (ORG_ID, LOWER(NAME)) WHERE STATUS = 'active';

CREATE TABLE IF NOT EXISTS EVENT (
  EVENT_ID   VARCHAR(64)  NOT NULL,
  ORG_ID     VARCHAR(128) NOT NULL,
  GROUP_ID   VARCHAR(128) NOT NULL,
  TOPIC_ID   VARCHAR(64)  NOT NULL,
  -- TEXT rather than JSONB: the payload is JSON this service serialises itself and only ever
  -- reads back whole, and JSONB would re-order its keys.
  PAYLOAD    TEXT         NOT NULL,
  CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_ID),
  CONSTRAINT UQ_EVENT_ORG_ID UNIQUE (ORG_ID, EVENT_ID),
  CONSTRAINT FK_E_ORG_TOPIC FOREIGN KEY (ORG_ID, TOPIC_ID) REFERENCES TOPIC (ORG_ID, TOPIC_ID)
);
CREATE INDEX IF NOT EXISTS IDX_E_TOPIC ON EVENT (TOPIC_ID);
CREATE INDEX IF NOT EXISTS IDX_EVENT_ORG_GROUP_TOPIC_CREATED ON EVENT (ORG_ID, GROUP_ID, TOPIC_ID, CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_EVENT_ORG_CREATED ON EVENT (ORG_ID, CREATED_AT DESC);
CREATE INDEX IF NOT EXISTS IDX_EVENT_ORG_TOPIC ON EVENT (ORG_ID, TOPIC_ID);

CREATE TABLE IF NOT EXISTS EVENT_PURPOSE (
  EVENT_ID     VARCHAR(64)  NOT NULL,
  ORG_ID       VARCHAR(128) NOT NULL,
  PURPOSE_NAME VARCHAR(128) NOT NULL,
  PRIMARY KEY (EVENT_ID, PURPOSE_NAME),
  CONSTRAINT FK_EVENT_PURPOSES_EVENT FOREIGN KEY (ORG_ID, EVENT_ID)
      REFERENCES EVENT (ORG_ID, EVENT_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS IDX_EVENT_PURPOSE_NAME ON EVENT_PURPOSE (PURPOSE_NAME);
CREATE INDEX IF NOT EXISTS IDX_EP_ORG ON EVENT_PURPOSE (ORG_ID, EVENT_ID);

CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
  SUBSCRIPTION_ID     VARCHAR(64)  NOT NULL,
  ORG_ID              VARCHAR(128) NOT NULL,
  GROUP_ID            VARCHAR(128) NOT NULL,
  NAME                VARCHAR(225) NOT NULL,
  STATUS              VARCHAR(32)  NOT NULL DEFAULT 'active',
  PURPOSE_FILTER_MODE VARCHAR(32)  NOT NULL,
  PURPOSE_SET_HASH    VARCHAR(64)  NOT NULL DEFAULT '',
  CALLBACK_URL        VARCHAR(512) DEFAULT NULL,
  SHARED_SECRET       VARCHAR(512) DEFAULT NULL,
  CREATED_AT          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELIVERY_MODE       VARCHAR(32)  NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID),
  CONSTRAINT UQ_SUB_ORG_ID UNIQUE (ORG_ID, SUBSCRIPTION_ID),
  CONSTRAINT CHK_S_STATUS CHECK (STATUS IN ('active', 'pending', 'stale', 'deleted')),
  CONSTRAINT CHK_SM_DELIVERY_MODE CHECK (DELIVERY_MODE IN ('webhook', 'poll'))
);
-- Same rule as mysql.sql's generated ACTIVE_NAME key: names are unique per org,
-- case-insensitively, until the subscription is deleted. SubscriptionDAOImpl recognises
-- a clash by this index's name, so it must stay UQ_SUB_ORG_ACTIVE_NAME.
CREATE UNIQUE INDEX IF NOT EXISTS UQ_SUB_ORG_ACTIVE_NAME ON SUBSCRIPTION (ORG_ID, LOWER(NAME)) WHERE STATUS <> 'deleted';
CREATE INDEX IF NOT EXISTS IDX_SUB_STATUS_UPDATED ON SUBSCRIPTION (STATUS, UPDATED_AT);
CREATE INDEX IF NOT EXISTS IDX_SUB_MATCHING ON SUBSCRIPTION (ORG_ID, GROUP_ID, STATUS);
DROP TRIGGER IF EXISTS TRG_SUBSCRIPTION_UPDATED_AT ON SUBSCRIPTION;
CREATE TRIGGER TRG_SUBSCRIPTION_UPDATED_AT BEFORE UPDATE ON SUBSCRIPTION
  FOR EACH ROW EXECUTE FUNCTION DPDP_TOUCH_UPDATED_AT();

CREATE TABLE IF NOT EXISTS SUBSCRIPTION_TOPIC (
  ORG_ID          VARCHAR(128) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(64)  NOT NULL,
  TOPIC_ID        VARCHAR(64)  NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID, TOPIC_ID),
  CONSTRAINT FK_ST_SUB FOREIGN KEY (ORG_ID, SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (ORG_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_ST_TOPIC FOREIGN KEY (ORG_ID, TOPIC_ID) REFERENCES TOPIC (ORG_ID, TOPIC_ID)
);
CREATE INDEX IF NOT EXISTS IDX_ST_TOPIC ON SUBSCRIPTION_TOPIC (ORG_ID, TOPIC_ID, SUBSCRIPTION_ID);
-- MySQL creates this one implicitly for FK_ST_SUB; PostgreSQL never indexes a foreign key itself.
CREATE INDEX IF NOT EXISTS IDX_ST_SUB ON SUBSCRIPTION_TOPIC (ORG_ID, SUBSCRIPTION_ID);

CREATE TABLE IF NOT EXISTS SUBSCRIPTION_PURPOSE (
  SUBSCRIPTION_ID VARCHAR(64)  NOT NULL,
  ORG_ID          VARCHAR(128) NOT NULL,
  PURPOSE_NAME    VARCHAR(128) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID, PURPOSE_NAME),
  CONSTRAINT FK_SUBSCRIPTION_PURPOSES_SUBSCRIPTION FOREIGN KEY (ORG_ID, SUBSCRIPTION_ID)
      REFERENCES SUBSCRIPTION (ORG_ID, SUBSCRIPTION_ID) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS IDX_SUB_PURPOSE_NAME ON SUBSCRIPTION_PURPOSE (PURPOSE_NAME);
CREATE INDEX IF NOT EXISTS IDX_SP_ORG ON SUBSCRIPTION_PURPOSE (ORG_ID, SUBSCRIPTION_ID);

CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY (
  DELIVERY_ID       VARCHAR(64) NOT NULL,
  ORG_ID            VARCHAR(128) NOT NULL,
  SUBSCRIPTION_ID   VARCHAR(64) NOT NULL,
  EVENT_ID          VARCHAR(64) NOT NULL,
  STATUS            VARCHAR(32) NOT NULL DEFAULT 'pending',
  ATTEMPT_COUNT     INTEGER     NOT NULL DEFAULT 0,
  NEXT_RETRY_AT     TIMESTAMP   NULL DEFAULT NULL,
  CREATED_AT        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT        TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELIVERED_AT      TIMESTAMP   NULL DEFAULT NULL,
  PRIMARY KEY (DELIVERY_ID),
  CONSTRAINT UQ_EDP_EVENT_SUB UNIQUE (EVENT_ID, SUBSCRIPTION_ID),
  CONSTRAINT UQ_WD_ORG_DELIVERY UNIQUE (ORG_ID, DELIVERY_ID),
  CONSTRAINT FK_EDP_EVENT FOREIGN KEY (ORG_ID, EVENT_ID) REFERENCES EVENT (ORG_ID, EVENT_ID),
  CONSTRAINT FK_WD_ORG_SUB FOREIGN KEY (ORG_ID, SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (ORG_ID, SUBSCRIPTION_ID),
  CONSTRAINT CHK_WEBHOOK_DELIVERY_STATUS CHECK (STATUS IN ('pending', 'in_flight', 'delivered', 'completed', 'failed'))
);
CREATE INDEX IF NOT EXISTS IDX_EDP_SUB ON WEBHOOK_DELIVERY (SUBSCRIPTION_ID);
CREATE INDEX IF NOT EXISTS IDX_WD_ORG ON WEBHOOK_DELIVERY (ORG_ID, SUBSCRIPTION_ID);
-- MySQL creates this one implicitly for its (ORG_ID, EVENT_ID) foreign key; PostgreSQL never
-- indexes a foreign key itself.
CREATE INDEX IF NOT EXISTS IDX_WD_ORG_EVENT ON WEBHOOK_DELIVERY (ORG_ID, EVENT_ID);
DROP TRIGGER IF EXISTS TRG_WEBHOOK_DELIVERY_UPDATED_AT ON WEBHOOK_DELIVERY;
CREATE TRIGGER TRG_WEBHOOK_DELIVERY_UPDATED_AT BEFORE UPDATE ON WEBHOOK_DELIVERY
  FOR EACH ROW EXECUTE FUNCTION DPDP_TOUCH_UPDATED_AT();

CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_ACK (
  ACK_ID              VARCHAR(64)  NOT NULL,
  DELIVERY_ID         VARCHAR(64)  NOT NULL,
  ORG_ID              VARCHAR(128) NOT NULL,
  COMPLETED_AT        TIMESTAMP    NULL DEFAULT NULL,
  COMPLETION_STATUS   VARCHAR(32)  NOT NULL,
  COMPLETION_EVIDENCE VARCHAR(512) NOT NULL,
  PRIMARY KEY (ACK_ID),
  CONSTRAINT UQ_EDA_DELIVERY UNIQUE (DELIVERY_ID),
  CONSTRAINT FK_EDA_DELIVERY FOREIGN KEY (ORG_ID, DELIVERY_ID) REFERENCES WEBHOOK_DELIVERY (ORG_ID, DELIVERY_ID),
  CONSTRAINT CHK_EDA_COMPLETION_STATUS CHECK (COMPLETION_STATUS IN ('completed', 'ack', 'disputed', 'partial'))
);
CREATE INDEX IF NOT EXISTS IDX_EDA_COMPLETION_STATUS ON WEBHOOK_DELIVERY_ACK (COMPLETION_STATUS);
CREATE INDEX IF NOT EXISTS IDX_WDA_ORG ON WEBHOOK_DELIVERY_ACK (ORG_ID, DELIVERY_ID);

CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_AUDIT (
  AUDIT_ID      VARCHAR(64)  NOT NULL,
  EVENT_ID      VARCHAR(64)  DEFAULT NULL,
  DELIVERY_ID   VARCHAR(64)  DEFAULT NULL,
  ORG_ID        VARCHAR(128) NOT NULL,
  RESPONSE_CODE VARCHAR(16)  DEFAULT NULL,
  CREATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATTEMPT_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (AUDIT_ID),
  CONSTRAINT FK_EA_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES WEBHOOK_DELIVERY (DELIVERY_ID) ON DELETE SET NULL,
  CONSTRAINT FK_EA_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS IDX_EA_DELIVERY ON WEBHOOK_DELIVERY_AUDIT (DELIVERY_ID, ATTEMPT_AT);
CREATE INDEX IF NOT EXISTS IDX_EA_EVENT ON WEBHOOK_DELIVERY_AUDIT (EVENT_ID);

CREATE TABLE IF NOT EXISTS POLL_DELIVERY (
  DELIVERY_ID     VARCHAR(64)   NOT NULL,
  ORG_ID          VARCHAR(128)  NOT NULL,
  SUBSCRIPTION_ID VARCHAR(64)   NOT NULL,
  EVENT_ID        VARCHAR(64)   NOT NULL,
  STATUS          VARCHAR(32)   NOT NULL DEFAULT 'pending',
  ERROR_CODE      VARCHAR(64)   DEFAULT NULL,
  ERROR_DETAIL    VARCHAR(1024) DEFAULT NULL,
  CREATED_AT      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COMPLETED_AT    TIMESTAMP     NULL DEFAULT NULL,
  PRIMARY KEY (DELIVERY_ID),
  CONSTRAINT UQ_EDPL_EVENT_SUB UNIQUE (EVENT_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_EDPL_EVENT FOREIGN KEY (ORG_ID, EVENT_ID) REFERENCES EVENT (ORG_ID, EVENT_ID),
  CONSTRAINT FK_PD_ORG_SUB FOREIGN KEY (ORG_ID, SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (ORG_ID, SUBSCRIPTION_ID),
  CONSTRAINT CHK_POLL_DELIVERY_STATUS CHECK (STATUS IN ('pending', 'acknowledged', 'err'))
);
CREATE INDEX IF NOT EXISTS IDX_EDPL_SUB ON POLL_DELIVERY (SUBSCRIPTION_ID, STATUS, CREATED_AT);
CREATE INDEX IF NOT EXISTS IDX_PD_ORG ON POLL_DELIVERY (ORG_ID, SUBSCRIPTION_ID);
-- MySQL creates this one implicitly for its (ORG_ID, EVENT_ID) foreign key; PostgreSQL never
-- indexes a foreign key itself.
CREATE INDEX IF NOT EXISTS IDX_PD_ORG_EVENT ON POLL_DELIVERY (ORG_ID, EVENT_ID);
