/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

-- PostgreSQL DDL definition for DPDP Event Notifications Service

CREATE OR REPLACE FUNCTION dpdp_set_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$;

-- TOPIC definition
CREATE TABLE IF NOT EXISTS TOPIC (
  TOPIC_ID varchar(64) NOT NULL,
  ORG_ID varchar(128) NOT NULL,
  NAME varchar(225) NOT NULL,
  DESCRIPTION varchar(255) DEFAULT NULL,
  STATUS varchar(32) NOT NULL DEFAULT 'active' CHECK (STATUS IN ('active', 'deregistered')),
  INITIATED_BY varchar(32) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (TOPIC_ID)
);

ALTER TABLE TOPIC DROP CONSTRAINT IF EXISTS UQ_TOPIC_ORG_NAME;
DROP INDEX IF EXISTS UQ_TOPIC_ORG_NAME_STATUS;
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TOPIC_ORG_ACTIVE_NAME
  ON TOPIC (ORG_ID, LOWER(NAME)) WHERE STATUS = 'active';

-- EVENT definition
CREATE TABLE IF NOT EXISTS EVENT (
  EVENT_ID varchar(64) NOT NULL,
  ORG_ID varchar(128) NOT NULL,
  GROUP_ID varchar(128) NOT NULL,
  TOPIC_ID varchar(64) NOT NULL,
  PAYLOAD jsonb NOT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_ID),
  CONSTRAINT FK_E_TOPIC FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC (TOPIC_ID)
);

CREATE INDEX IF NOT EXISTS IDX_EVENT_ORG_GROUP_TOPIC_CREATED ON EVENT (ORG_ID, GROUP_ID, TOPIC_ID, CREATED_AT);

-- EVENT_PURPOSE definition
CREATE TABLE IF NOT EXISTS EVENT_PURPOSE (
  EVENT_ID varchar(64) NOT NULL,
  PURPOSE_NAME varchar(128) NOT NULL,
  PRIMARY KEY (EVENT_ID, PURPOSE_NAME),
  CONSTRAINT FK_EVENT_PURPOSES_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_EVENT_PURPOSE_NAME ON EVENT_PURPOSE (PURPOSE_NAME);

-- SUBSCRIPTION definition
CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
  SUBSCRIPTION_ID varchar(64) NOT NULL,
  ORG_ID varchar(128) NOT NULL,
  GROUP_ID varchar(128) NOT NULL,
  TOPIC_ID varchar(64) NOT NULL,
  STATUS varchar(32) NOT NULL DEFAULT 'active',
  PURPOSE_FILTER_MODE varchar(32) NOT NULL,
  PURPOSE_SET_HASH varchar(64) NOT NULL DEFAULT '',
  CALLBACK_URL varchar(512) DEFAULT NULL,
  SHARED_SECRET varchar(512) DEFAULT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELIVERY_MODE varchar(32) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID),
  CONSTRAINT FK_S_TOPIC FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC (TOPIC_ID),
  CONSTRAINT CHK_S_STATUS CHECK (STATUS IN ('active', 'pending', 'stale', 'deleted')),
  CONSTRAINT CHK_SM_DELIVERY_MODE CHECK (DELIVERY_MODE IN ('webhook', 'poll'))
);

CREATE INDEX IF NOT EXISTS IDX_SUB_STATUS_UPDATED ON SUBSCRIPTION (STATUS, UPDATED_AT);
CREATE INDEX IF NOT EXISTS IDX_SUB_MATCHING ON SUBSCRIPTION (ORG_ID, GROUP_ID, TOPIC_ID, STATUS);



DROP TRIGGER IF EXISTS trg_subscription_updated_at ON SUBSCRIPTION;
CREATE TRIGGER trg_subscription_updated_at
  BEFORE UPDATE ON SUBSCRIPTION
  FOR EACH ROW EXECUTE FUNCTION dpdp_set_updated_at();

-- SUBSCRIPTION_PURPOSE definition
CREATE TABLE IF NOT EXISTS SUBSCRIPTION_PURPOSE (
  SUBSCRIPTION_ID varchar(64) NOT NULL,
  PURPOSE_NAME varchar(128) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID, PURPOSE_NAME),
  CONSTRAINT FK_SUBSCRIPTION_PURPOSES_SUBSCRIPTION FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (SUBSCRIPTION_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_SUB_PURPOSE_NAME ON SUBSCRIPTION_PURPOSE (PURPOSE_NAME);

-- WEBHOOK_DELIVERY definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY (
  DELIVERY_ID varchar(64) NOT NULL,
  SUBSCRIPTION_ID varchar(64) NOT NULL,
  EVENT_ID varchar(64) NOT NULL,
  STATUS varchar(32) NOT NULL DEFAULT 'pending',
  ATTEMPT_COUNT int NOT NULL DEFAULT 0,
  MANUAL_RETRY_USED boolean NOT NULL DEFAULT false,
  NEXT_RETRY_AT timestamp NULL DEFAULT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELIVERED_AT timestamp NULL DEFAULT NULL,
  PRIMARY KEY (DELIVERY_ID),
  CONSTRAINT UQ_EDP_EVENT_SUB UNIQUE (EVENT_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_EDP_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID),
  CONSTRAINT FK_EDP_SUB FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (SUBSCRIPTION_ID),
  CONSTRAINT CHK_WEBHOOK_DELIVERY_STATUS CHECK (STATUS IN ('pending', 'in_flight', 'delivered', 'completed', 'failed'))
);

CREATE INDEX IF NOT EXISTS IDX_EDP_SUB ON WEBHOOK_DELIVERY (SUBSCRIPTION_ID);

DROP TRIGGER IF EXISTS trg_webhook_delivery_updated_at ON WEBHOOK_DELIVERY;
CREATE TRIGGER trg_webhook_delivery_updated_at
  BEFORE UPDATE ON WEBHOOK_DELIVERY
  FOR EACH ROW EXECUTE FUNCTION dpdp_set_updated_at();

-- WEBHOOK_DELIVERY_ACK definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_ACK (
  ACK_ID varchar(64) NOT NULL,
  DELIVERY_ID varchar(64) NOT NULL,
  COMPLETED_AT timestamp NULL DEFAULT NULL,
  COMPLETION_STATUS varchar(32) NOT NULL,
  COMPLETION_EVIDENCE varchar(512) NOT NULL,
  PRIMARY KEY (ACK_ID),
  CONSTRAINT UQ_EDA_DELIVERY UNIQUE (DELIVERY_ID),
  CONSTRAINT FK_EDA_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES WEBHOOK_DELIVERY (DELIVERY_ID),
  CONSTRAINT CHK_EDA_COMPLETION_STATUS CHECK (COMPLETION_STATUS IN ('completed', 'ack', 'disputed', 'partial'))
);

CREATE INDEX IF NOT EXISTS IDX_EDA_COMPLETION_STATUS ON WEBHOOK_DELIVERY_ACK (COMPLETION_STATUS);
CREATE INDEX IF NOT EXISTS IDX_EDA_DELIVERY ON WEBHOOK_DELIVERY_ACK (DELIVERY_ID);

-- WEBHOOK_DELIVERY_AUDIT definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_AUDIT (
  AUDIT_ID varchar(64) NOT NULL,
  EVENT_ID varchar(64) DEFAULT NULL,
  DELIVERY_ID varchar(64) DEFAULT NULL,
  ORG_ID varchar(128) NOT NULL,
  RESPONSE_CODE varchar(16) DEFAULT NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATTEMPT_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (AUDIT_ID),
  CONSTRAINT FK_EA_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES WEBHOOK_DELIVERY (DELIVERY_ID) ON DELETE SET NULL,
  CONSTRAINT FK_EA_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_EA_DELIVERY ON WEBHOOK_DELIVERY_AUDIT (DELIVERY_ID, ATTEMPT_AT);
CREATE INDEX IF NOT EXISTS IDX_EA_EVENT ON WEBHOOK_DELIVERY_AUDIT (EVENT_ID);

-- POLL_DELIVERY definition
CREATE TABLE IF NOT EXISTS POLL_DELIVERY (
  DELIVERY_ID varchar(64) NOT NULL,
  SUBSCRIPTION_ID varchar(64) NOT NULL,
  EVENT_ID varchar(64) NOT NULL,
  STATUS varchar(32) NOT NULL DEFAULT 'pending',
  ERROR_CODE varchar(64) NULL,
  ERROR_DETAIL varchar(1024) NULL,
  CREATED_AT timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COMPLETED_AT timestamp NULL DEFAULT NULL,
  PRIMARY KEY (DELIVERY_ID),
  CONSTRAINT UQ_EDPL_EVENT_SUB UNIQUE (EVENT_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_EDPL_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID),
  CONSTRAINT FK_EDPL_SUB FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (SUBSCRIPTION_ID),
  CONSTRAINT CHK_POLL_DELIVERY_STATUS CHECK (STATUS IN ('pending', 'acknowledged', 'err'))
);

CREATE INDEX IF NOT EXISTS IDX_EDPL_SUB ON POLL_DELIVERY (SUBSCRIPTION_ID, STATUS, CREATED_AT);
