/**
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

-- SQLite DDL definition for DPDP Event Notifications Service

PRAGMA foreign_keys = ON;

-- TOPIC definition
CREATE TABLE IF NOT EXISTS TOPIC (
  TOPIC_ID VARCHAR(64) NOT NULL,
  ORG_ID VARCHAR(128) NOT NULL,
  NAME VARCHAR(225) NOT NULL,
  DESCRIPTION VARCHAR(255) DEFAULT NULL,
  STATUS VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (STATUS IN ('active', 'deregistered')),
  INITIATED_BY VARCHAR(32) NOT NULL DEFAULT 'USER',
  PRIMARY KEY (TOPIC_ID)
);

DROP INDEX IF EXISTS UQ_TOPIC_ORG_NAME_STATUS;
CREATE UNIQUE INDEX IF NOT EXISTS UQ_TOPIC_ORG_ACTIVE_NAME
  ON TOPIC (ORG_ID, LOWER(NAME)) WHERE STATUS = 'active';

-- EVENT definition
CREATE TABLE IF NOT EXISTS EVENT (
  EVENT_ID VARCHAR(64) NOT NULL,
  ORG_ID VARCHAR(128) NOT NULL,
  GROUP_ID VARCHAR(128) NOT NULL,
  TOPIC_ID VARCHAR(64) NOT NULL,
  PAYLOAD TEXT NOT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (EVENT_ID),
  CONSTRAINT FK_E_TOPIC FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC (TOPIC_ID)
);

CREATE INDEX IF NOT EXISTS IDX_EVENT_ORG_GROUP_TOPIC_CREATED ON EVENT (ORG_ID, GROUP_ID, TOPIC_ID, CREATED_AT);

-- EVENT_PURPOSE definition
CREATE TABLE IF NOT EXISTS EVENT_PURPOSE (
  EVENT_ID VARCHAR(64) NOT NULL,
  PURPOSE_NAME VARCHAR(128) NOT NULL,
  PRIMARY KEY (EVENT_ID, PURPOSE_NAME),
  CONSTRAINT FK_EVENT_PURPOSES_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_EVENT_PURPOSE_NAME ON EVENT_PURPOSE (PURPOSE_NAME);

-- SUBSCRIPTION definition
CREATE TABLE IF NOT EXISTS SUBSCRIPTION (
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  ORG_ID VARCHAR(128) NOT NULL,
  GROUP_ID VARCHAR(128) NOT NULL,
  TOPIC_ID VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) NOT NULL DEFAULT 'active' CHECK (STATUS IN ('active', 'pending', 'stale', 'deleted')),
  PURPOSE_FILTER_MODE VARCHAR(32) NOT NULL,
  PURPOSE_SET_HASH VARCHAR(64) NOT NULL DEFAULT '',
  CALLBACK_URL VARCHAR(512) DEFAULT NULL,
  SHARED_SECRET VARCHAR(512) DEFAULT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELIVERY_MODE VARCHAR(32) NOT NULL CHECK (DELIVERY_MODE IN ('webhook', 'poll')),
  PRIMARY KEY (SUBSCRIPTION_ID),
  CONSTRAINT FK_S_TOPIC FOREIGN KEY (TOPIC_ID) REFERENCES TOPIC (TOPIC_ID)
);

CREATE INDEX IF NOT EXISTS IDX_SUB_STATUS_UPDATED ON SUBSCRIPTION (STATUS, UPDATED_AT);
CREATE INDEX IF NOT EXISTS IDX_SUB_MATCHING ON SUBSCRIPTION (ORG_ID, GROUP_ID, TOPIC_ID, STATUS);



CREATE TRIGGER IF NOT EXISTS TRG_SUBSCRIPTION_UPDATED_AT
AFTER UPDATE ON SUBSCRIPTION
FOR EACH ROW
BEGIN
  UPDATE SUBSCRIPTION SET UPDATED_AT = CURRENT_TIMESTAMP WHERE SUBSCRIPTION_ID = NEW.SUBSCRIPTION_ID;
END;

-- SUBSCRIPTION_PURPOSE definition
CREATE TABLE IF NOT EXISTS SUBSCRIPTION_PURPOSE (
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  PURPOSE_NAME VARCHAR(128) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID, PURPOSE_NAME),
  CONSTRAINT FK_SUBSCRIPTION_PURPOSES_SUBSCRIPTION FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (SUBSCRIPTION_ID) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS IDX_SUB_PURPOSE_NAME ON SUBSCRIPTION_PURPOSE (PURPOSE_NAME);

-- WEBHOOK_DELIVERY definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY (
  DELIVERY_ID VARCHAR(64) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (STATUS IN ('pending', 'in_flight', 'delivered', 'completed', 'failed')),
  ATTEMPT_COUNT INTEGER NOT NULL DEFAULT 0,
  MANUAL_RETRY_USED INTEGER NOT NULL DEFAULT 0 CHECK (MANUAL_RETRY_USED IN (0, 1)),
  NEXT_RETRY_AT TIMESTAMP NULL DEFAULT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  DELIVERED_AT TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (DELIVERY_ID),
  CONSTRAINT UQ_EDP_EVENT_SUB UNIQUE (EVENT_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_EDP_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID),
  CONSTRAINT FK_EDP_SUB FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (SUBSCRIPTION_ID)
);

CREATE INDEX IF NOT EXISTS IDX_EDP_SUB ON WEBHOOK_DELIVERY (SUBSCRIPTION_ID);

CREATE TRIGGER IF NOT EXISTS TRG_WEBHOOK_DELIVERY_UPDATED_AT
AFTER UPDATE ON WEBHOOK_DELIVERY
FOR EACH ROW
BEGIN
  UPDATE WEBHOOK_DELIVERY SET UPDATED_AT = CURRENT_TIMESTAMP WHERE DELIVERY_ID = NEW.DELIVERY_ID;
END;

-- WEBHOOK_DELIVERY_ACK definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_ACK (
  ACK_ID VARCHAR(64) NOT NULL,
  DELIVERY_ID VARCHAR(64) NOT NULL,
  COMPLETED_AT TIMESTAMP NULL DEFAULT NULL,
  COMPLETION_STATUS VARCHAR(32) NOT NULL CHECK (COMPLETION_STATUS IN ('completed', 'ack', 'disputed', 'partial')),
  COMPLETION_EVIDENCE VARCHAR(512) NOT NULL,
  PRIMARY KEY (ACK_ID),
  CONSTRAINT UQ_EDA_DELIVERY UNIQUE (DELIVERY_ID),
  CONSTRAINT FK_EDA_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES WEBHOOK_DELIVERY (DELIVERY_ID)
);

CREATE INDEX IF NOT EXISTS IDX_EDA_COMPLETION_STATUS ON WEBHOOK_DELIVERY_ACK (COMPLETION_STATUS);
CREATE INDEX IF NOT EXISTS IDX_EDA_DELIVERY ON WEBHOOK_DELIVERY_ACK (DELIVERY_ID);

-- WEBHOOK_DELIVERY_AUDIT definition
CREATE TABLE IF NOT EXISTS WEBHOOK_DELIVERY_AUDIT (
  AUDIT_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(64) DEFAULT NULL,
  DELIVERY_ID VARCHAR(64) DEFAULT NULL,
  ORG_ID VARCHAR(128) NOT NULL,
  RESPONSE_CODE VARCHAR(16) DEFAULT NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ATTEMPT_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (AUDIT_ID),
  CONSTRAINT FK_EA_DELIVERY FOREIGN KEY (DELIVERY_ID) REFERENCES WEBHOOK_DELIVERY (DELIVERY_ID) ON DELETE SET NULL,
  CONSTRAINT FK_EA_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS IDX_EA_DELIVERY ON WEBHOOK_DELIVERY_AUDIT (DELIVERY_ID, ATTEMPT_AT);
CREATE INDEX IF NOT EXISTS IDX_EA_EVENT ON WEBHOOK_DELIVERY_AUDIT (EVENT_ID);

-- POLL_DELIVERY definition
CREATE TABLE IF NOT EXISTS POLL_DELIVERY (
  DELIVERY_ID VARCHAR(64) NOT NULL,
  SUBSCRIPTION_ID VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR(64) NOT NULL,
  STATUS VARCHAR(32) NOT NULL DEFAULT 'pending' CHECK (STATUS IN ('pending', 'acknowledged', 'err')),
  ERROR_CODE VARCHAR(64) NULL,
  ERROR_DETAIL VARCHAR(1024) NULL,
  CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  COMPLETED_AT TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (DELIVERY_ID),
  CONSTRAINT UQ_EDPL_EVENT_SUB UNIQUE (EVENT_ID, SUBSCRIPTION_ID),
  CONSTRAINT FK_EDPL_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENT (EVENT_ID),
  CONSTRAINT FK_EDPL_SUB FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES SUBSCRIPTION (SUBSCRIPTION_ID)
);

CREATE INDEX IF NOT EXISTS IDX_EDPL_SUB ON POLL_DELIVERY (SUBSCRIPTION_ID, STATUS, CREATED_AT);
